[build-system]
requires = ["hatchling>=1.0.0"]
build-backend = "hatchling.build"

[project]
name = "pubchem-mcp"
version = "0.1.0"
requires-python = ">=3.8"

[tool.hatch.build.targets.wheel]
packages = ["src/pubchem_mcp"]
